In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
dataset=dataset.iloc[:,3:]

In [5]:
dataset.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [7]:
dataset.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
dataset.duplicated().sum()

0

In [10]:
dataset['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [11]:
dataset['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [12]:
dataset=pd.get_dummies(dataset,columns=['Geography','Gender'])

In [13]:
dataset.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False

In [14]:
dataset.drop(columns=['Geography_Spain','Gender_Female'],axis=1,inplace=True)

In [15]:
dataset.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,True,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,False
2,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,True,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,False

In [16]:
dataset['Geography_France']=np.where(dataset['Geography_France']==True,1,0)
dataset['Geography_Germany']=np.where(dataset['Geography_Germany']==True,1,0)
dataset['Gender_Male']=np.where(dataset['Gender_Male']==True,1,0)

In [17]:
dataset.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,0

In [18]:
x=dataset.drop(columns=['Exited'])
y=dataset['Exited']

In [19]:
x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0

In [20]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [22]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 11)
(2000, 11)
(8000,)
(2000,)

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [26]:
pd.DataFrame(x_train_scaled).head()

,0,1,2,3,4,5,6,7,8,9,10
0,-0.230820,-0.944500,-0.701742,0.588173,0.802257,-1.553374,0.977259,0.427394,-0.998501,1.714901,0.915091
1,-0.251509,-0.944500,-0.355203,0.469849,0.802257,-1.553374,-1.023271,-1.025487,1.001501,-0.583124,-1.092788
2,-0.396330,0.774987,0.337876,0.858788,-0.911510,0.643760,0.977259,-0.944798,-0.998501,1.714901,-1.092788
3,-0.044622,1.252622,0.337876,0.565604,0.802257,-1.553374,0.977259,-0.551946,-0.998501,1.714901,-1.092788
4,0.658795,-0.562392,1.030954,0.730395,-0.911510,-1.553374,-1.023271,1.083383,-0.998501,-0.583124,0.915091

In [24]:
x_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ..., -0.99850112,
         1.71490137,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ...,  1.00150113,
        -0.58312392, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ..., -0.99850112,
         1.71490137, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ...,  1.00150113,
        -0.58312392, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ...,  1.00150113,
        -0.58312392, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ..., -0.99850112,
         1.71490137,  0.91509065]])

In [25]:
x_test_scaled

array([[-1.03768121,  0.77498705, -1.0482813 , ...,  1.00150113,
        -0.58312392,  0.91509065],
       [ 0.30708683, -0.46686456, -0.70174202, ...,  1.00150113,
        -0.58312392,  0.91509065],
       [-1.23422423,  0.29735181, -1.0482813 , ...,  1.00150113,
        -0.58312392, -1.09278791],
       ...,
       [-0.86182692, -0.46686456,  1.72403288, ..., -0.99850112,
        -0.58312392,  0.91509065],
       [-0.30323097, -0.84897275, -1.0482813 , ..., -0.99850112,
         1.71490137, -1.09278791],
       [ 0.04847759,  1.25262228,  1.3774936 , ..., -0.99850112,
         1.71490137,  0.91509065]])

In [27]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import *

In [31]:
!pip install keras-tuner --upgrade

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (3.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (1.26.4)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (3.12.1)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (0.13.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.10/dist-packages (from keras->keras-tuner) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.12.14)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from optree->keras->keras-tuner) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras->keras-tuner) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 5.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [32]:
import keras_tuner as kt

In [33]:
def build_model(hp):
  model=Sequential()
  counter=0

  for i in range(hp.Int('num_layers',min_value=1,max_value=5)):
    if counter==0:
      model.add(Dense(hp.Int('Num_neurons'+str(i),min_value=4,max_value=128,step=4),
                      activation=hp.Choice('activation'+str(i),values=['relu','leaky_relu']),input_dim=11))#weight_initialization same as activation
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.25,0.3,0.35,0.4,0.45,0.5])))

    else:
      model.add(Dense(hp.Int('Num_neurons'+str(i),min_value=4,max_value=128,step=4),
                      activation=hp.Choice('activation'+str(i),values=['relu','leaky_relu'])))
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.25,0.3,0.35,0.4,0.45,0.5])))
    counter+=1
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-2,1e-3,1e-4])),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [34]:
tuner=kt.RandomSearch(
   build_model,
   objective='val_accuracy',
   max_trials=5,
   directory='mydir',
   project_name='myproject'
)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
tuner.search(x_train_scaled,y_train,epochs=5,validation_data=(x_test_scaled,y_test))

Trial 5 Complete [00h 00m 06s]
val_accuracy: 0.8054999709129333

Best val_accuracy So Far: 0.8554999828338623
Total elapsed time: 00h 00m 37s

In [36]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:713: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 112)                 │           1,344 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 112)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             113 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,457 (5.69 KB)

 Trainable params: 1,457 (5.69 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'Num_neurons0': 112,
 'activation0': 'leaky_relu',
 'dropout0': 0.5,
 'learning_rate': 0.01}

In [39]:
model.fit(x_train_scaled,y_train,epochs=50,initial_epoch=6,validation_data=(x_test_scaled,y_test))#initial_epoch=5

Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8498 - loss: 0.3729 - val_accuracy: 0.8535 - val_loss: 0.3559
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8443 - loss: 0.3769 - val_accuracy: 0.8490 - val_loss: 0.3512
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8423 - loss: 0.3868 - val_accuracy: 0.8530 - val_loss: 0.3566
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8468 - loss: 0.3719 - val_accuracy: 0.8585 - val_loss: 0.3485
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8457 - loss: 0.3701 - val_accuracy: 0.8490 - val_loss: 0.3674
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8417 - loss: 0.3755 - val_accuracy: 0.8520 - val_loss: 0.3648
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8364 - loss: 0.3950 - val_accuracy: 0.8555 - val_loss: 0.3603
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8449 - loss: 0.3725 - val_accuracy: 0.8550 - val_loss: 0.3498
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8487 - loss: 0.3706 - val_accuracy: 0.8515 - val_loss: 0.3611
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8435 - loss: 0.3856 - val_accuracy: 0.8480 - val_loss: 0.3512
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8440 - loss: 0.3744 - val_accuracy: 0.8575 - val_loss: 0.3476
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8410 - loss: 0.3792 - val_accuracy: 0.8580 - val_loss: 0.3447
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8461 - loss: 0.3772 - val_accuracy: 0.8575 - val_loss: 0.3446
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8497 - loss: 0.3629 - val_accuracy: 0.8495 - val_loss: 0.3602
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8504 - loss: 0.3697 - val_accuracy: 0.8535 - val_loss: 0.3476
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8560 - loss: 0.3618 - val_accuracy: 0.8590 - val_loss: 0.3452
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8498 - loss: 0.3650 - val_accuracy: 0.8585 - val_loss: 0.3503
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8413 - loss: 0.3791 - val_accuracy: 0.8530 - val_loss: 0.3447
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8425 - loss: 0.3843 - val_accuracy: 0.8570 - val_loss: 0.3433
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8513 - loss: 0.3668 - val_accuracy: 0.8510 - val_loss: 0.3536
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8445 - loss: 0.3794 - val_accuracy: 0.8570 - val_loss: 0.3385
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8497 - loss: 0.3627 - val_accuracy: 0.8520 - val_loss: 0.3429
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8468 - loss: 0.3741 - val_accuracy: 0.8550 - val_loss: 0.3512
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3895 - val_accuracy: 0.8515 - val_loss: 0.3473
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8385 - loss: 0.3884 - val_accuracy: 0.8555 - val_loss: 0.3551
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8500 - loss: 0.3659 - val_accuracy: 0.8630 - val_loss: 0.3425
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8483 - loss: 0.3717 - val_accuracy: 0.8545 - val_loss: 0.3543
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8536 - loss: 0.3647 - val_accuracy: 0.8580 - val_loss: 0.3497
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8515 - loss: 0.3709 - val_accuracy: 0.8565 - val_loss: 0.3441
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8407 - loss: 0.3832 - val_accuracy: 0.8485 - val_loss: 0.3612
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8500 - loss: 0.3636 - val_accuracy: 0.8565 - val_loss: 0.3495
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8518 - loss: 0.3717 - val_accuracy: 0.8595 - val_loss: 0.3446
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8489 - loss: 0.3752 - val_accuracy: 0.8485 - val_loss: 0.3703
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8371 - loss: 0.3876 - val_accuracy: 0.8625 - val_loss: 0.3417
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8417 - loss: 0.3793 - val_accuracy: 0.8600 - val_loss: 0.3473
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8505 - loss: 0.3713 - val_accuracy: 0.8595 - val_loss: 0.3405
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8450 - loss: 0.3716 - val_accuracy: 0.8550 - val_loss: 0.3461
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8478 - loss: 0.3685 - val_accuracy: 0.8600 - val_loss: 0.3370
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8414 - loss: 0.3753 - val_accuracy: 0.8570 - val_loss: 0.3487
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8536 - loss: 0.3600 - val_accuracy: 0.8610 - val_loss: 0.3548
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8403 - loss: 0.3836 - val_accuracy: 0.8600 - val_loss: 0.3387
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8421 - loss: 0.3809 - val_accuracy: 0.8625 - val_loss: 0.3362
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8433 - loss: 0.3788 - val_accuracy: 0.8555 - val_loss: 0.3481
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8429 - loss: 0.3779 - val_accuracy: 0.8550 - val_loss: 0.3501